/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rps;

/**
 *
 * @author dwayn
 */
public class rpsMenu extends javax.swing.JFrame {

    /**
     * Creates new form rpsMenu
     */
    public rpsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRock = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnScissors = new javax.swing.JButton();
        txfYouChose = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfComputerChose = new javax.swing.JTextField();
        lblWinOrLose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock, Paper, Scissors");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(1000, 563));
        setPreferredSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 40, 69));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rock, Paper, Scissors");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("By Dwayne Crous");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(332, 332, 332))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("You Chose:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        btnRock.setBackground(new java.awt.Color(101, 175, 255));
        btnRock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRock.setForeground(new java.awt.Color(0, 0, 0));
        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });
        getContentPane().add(btnRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, 50));

        btnPaper.setBackground(new java.awt.Color(101, 175, 255));
        btnPaper.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPaper.setForeground(new java.awt.Color(0, 0, 0));
        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 50));

        btnScissors.setBackground(new java.awt.Color(101, 175, 255));
        btnScissors.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScissors.setForeground(new java.awt.Color(0, 0, 0));
        btnScissors.setText("Scissors");
        btnScissors.setToolTipText("");
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });
        getContentPane().add(btnScissors, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 170, 50));

        txfYouChose.setEditable(false);
        txfYouChose.setBackground(new java.awt.Color(101, 175, 255));
        txfYouChose.setForeground(new java.awt.Color(0, 0, 0));
        txfYouChose.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfYouChose, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 320, 400, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose Between Rock, Paper or Scissors");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("The Computer Chose:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        txfComputerChose.setEditable(false);
        txfComputerChose.setBackground(new java.awt.Color(101, 175, 255));
        txfComputerChose.setForeground(new java.awt.Color(0, 0, 0));
        txfComputerChose.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfComputerChose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 400, -1));

        lblWinOrLose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWinOrLose.setForeground(new java.awt.Color(255, 255, 255));
        lblWinOrLose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblWinOrLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 250, 70));

        jPanel2.setBackground(new java.awt.Color(27, 40, 69));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dwayne Crous Development");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel7)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1000, 50));

        jPanel3.setBackground(new java.awt.Color(39, 64, 96));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        // TODO add your handling code here:
        txfYouChose.setText("Rock");
        int randomNum = (int) (Math.random() * 3 + 1);
        String cpuChoice = "";
        
        if(randomNum == 1) {
            System.out.println("1");
            cpuChoice = "Rock";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Tied!");
        } else if (randomNum == 2) {
            System.out.println("2");
            cpuChoice = "Paper";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Won!");
        } else if (randomNum == 3) {
            System.out.println("3");
            cpuChoice = "Scissors";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Lost!");
        }
    }//GEN-LAST:event_btnRockActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        // TODO add your handling code here:
        txfYouChose.setText("Paper");
        int randomNum = (int) (Math.random() * 3 + 1);
        String cpuChoice = "";
        
        if(randomNum == 1) {
            System.out.println("1");
            cpuChoice = "Rock";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Won!");
        } else if (randomNum == 2) {
            System.out.println("2");
            cpuChoice = "Paper";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Tied!");
        } else if (randomNum == 3) {
            System.out.println("3");
            cpuChoice = "Scissors";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Lost!");
        }
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed
        // TODO add your handling code here:
        txfYouChose.setText("Scissors");
        int randomNum = (int) (Math.random() * 3 + 1);
        String cpuChoice = "";
        
        if(randomNum == 1) {
            System.out.println("1");
            cpuChoice = "Rock";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Lost!");
        } else if (randomNum == 2) {
            System.out.println("2");
            cpuChoice = "Paper";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Won!");
        } else if (randomNum == 3) {
            System.out.println("3");
            cpuChoice = "Scissors";
            txfComputerChose.setText(cpuChoice);
            lblWinOrLose.setText("You Tied!");
        }
    }//GEN-LAST:event_btnScissorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblWinOrLose;
    private javax.swing.JTextField txfComputerChose;
    private javax.swing.JTextField txfYouChose;
    // End of variables declaration//GEN-END:variables
}
